# Import the Prisma client generated from our schema.prisma file.
# This client contains all the autogenerated Python code for interacting with our database.
from prisma import Prisma

# An asynchronous function to fetch a specific user and all of their items from the database.
# We use 'async def' because database queries take time over a network, 
# and we want our app to be able to do other things while waiting.
async def get_user_by_id(user_id: str):
    
    # We initialize an instance of the Prisma client.
    # This prepares the connection settings based on our Prisma schema.
    db = Prisma()
    
    # We await the connection to actually establish the connection to the PostgreSQL database.
    # Without this, we can't send queries.
    await db.connect()
    
    # We start a 'try' block because database operations can occasionally fail 
    # (e.g., if the network drops), and we want to ensure we disconnect gracefully later.
    try:
        # We call Prisma's generated 'find_unique' function on the 'user' model.
        # This translates to a highly optimized SQL query under the hood:
        # `SELECT * FROM "User" WHERE id = user_id;`
        user = await db.user.find_unique(
            
            # The 'where' clause tells Prisma exactly which row we are looking for.
            # Here, we are looking for a user whose 'id' column exactly matches our provided user_id.
            where={
                "id": user_id
            },
            
            # The 'include' clause is a massive benefit of using an ORM.
            # It tells Prisma to automatically perform a SQL JOIN to also fetch related data.
            # In this case, "items: True" tells Prisma to also fetch all Items belonging to this User.
            include={
                "items": True
            }
        )
        
        # After fetching, we return the Python object 'user' back to whoever called this function.
        # This object will have all the user's properties (like user.name, user.email) 
        # as well as a list of items (user.items).
        return user
        
    # The 'finally' block ensures this code runs no matter what happens, even if an error occurred above.
    finally:
        # We politely close the connection to the database.
        # If we don't do this, we'll leave open connections hanging, which can crash the database later.
        await db.disconnect()

# An asynchronous function to update the quantity of a specific item in a user's inventory.
async def update_item_quantity(item_id: str, new_quantity: int):
    
    # Initialize the Prisma client.
    db = Prisma()
    
    # Establish the connection to the PostgreSQL database.
    await db.connect()
    
    try:
        # We call Prisma's generated 'update' function on the 'item' model.
        # This translates to a SQL query like: 
        # `UPDATE "Item" SET quantity = new_quantity WHERE id = item_id;`
        updated_item = await db.item.update(
            
            # The 'where' clause identifies which exact item we want to update.
            # We are targeting the item whose 'id' matches our provided item_id.
            where={
                "id": item_id
            },
            
            # The 'data' clause specifies *what* we actually want to change about this item.
            # Here, we are setting the "quantity" column to our new_quantity variable.
            data={
                "quantity": new_quantity
            }
        )
        
        # Return the updated item object so the caller knows the operation succeeded 
        # and has access to the fresh data.
        return updated_item
        
    finally:
        # Always remember to disconnect and free up database resources!
        await db.disconnect()
