import json
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from langchain_core.messages import HumanMessage

from agent import app as graph_app
from api_schemas import ChatRequest

app = FastAPI(
    title="LangGraph Agent API",
    description="Streaming REST API for an autonomous tool-calling LangGraph agent."
)

# Configure CORS so our Next.js frontend can communicate with this API securely
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # In production, restrict this to your actual frontend URL (e.g., http://localhost:3000)
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/health")
async def health_check():
    """Simple health check endpoint."""
    return {"status": "ok"}

async def generate_chat_stream(message: str):
    """
    Generator function that invokes the LangGraph agent and yields 
    Server-Sent Events (SSE) detailing the agent's thought process,
    tool executions, and streaming text responses.
    """
    state = {"messages": [HumanMessage(content=message)]}
    
    # We use astream_events (v2) to get highly granular updates from the graph,
    # including token-by-token generation and precise tool start/end timestamps.
    async for event in graph_app.astream_events(state, version="v2"):
        kind = event["event"]
        
        # 1. Capture streaming text chunks generated by the LLM
        if kind == "on_chat_model_stream":
            content = event["data"]["chunk"].content
            if content:
                yield f"data: {json.dumps({'type': 'content', 'data': content})}\n\n"
                
        # 2. Capture when the agent decides to execute a backend tool
        elif kind == "on_tool_start":
            tool_name = event["name"]
            tool_input = event["data"].get("input", {})
            yield f"data: {json.dumps({'type': 'tool_start', 'tool': tool_name, 'input': tool_input})}\n\n"
            
        # 3. Capture when the agent finishes executing the backend tool
        elif kind == "on_tool_end":
            tool_name = event["name"]
            yield f"data: {json.dumps({'type': 'tool_end', 'tool': tool_name})}\n\n"
            
    # Always signify the end of the stream
    yield "data: [DONE]\n\n"

@app.post("/chat")
async def chat_endpoint(request: ChatRequest):
    """
    Primary endpoint that accepts user text and returns an asynchronous stream
    of the agent's actions and responses.
    """
    return StreamingResponse(
        generate_chat_stream(request.message),
        media_type="text/event-stream"
    )

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
